services:
  dropmi:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: dropmi-app
    container_name: dropmi
    user: "1000:1000"
    group_add:
      - "105"
    restart: no
    expose:
      - "8080"
    command:
      - "-config"
      - "/data/config/dropmi.cfg"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/craid1/docker-containers/dropMi/data:/data"
    depends_on:
      - music-tools
    networks:
      - cloudflare

  music-tools:
    build:
      context: .
      dockerfile: Dockerfile.music-tools
    image: music-tools
    container_name: music-tools
    user: "1000:1000"
    command: ["sleep", "infinity"]
    volumes:
      - "/mnt/craid1/docker-containers/dropMi/data:/data"

networks:
  cloudflare:
    external: true
